<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContentOS.Application\ContentOS.Application.csproj" />
    <ProjectReference Include="..\ContentOS.Contracts\ContentOS.Contracts.csproj" />
    <ProjectReference Include="..\ContentOS.Domain\ContentOS.Domain.csproj" />
    <ProjectReference Include="..\ContentOS.SharedKernel\ContentOS.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.Postgresql" />
  </ItemGroup>

</Project>
